
server.port=8080

spring.datasource.url=jdbc:oracle:thin:@localhost:15211/XEPDB1
spring.datasource.username=tienda
spring.datasource.password=tienda123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.thymeleaf.cache=false

firebase.json.path=firebase

firebase.json.file=serviceAccountKey.json

firebase.bucket.name=techshop.appspot.com


firebase.storage.path=techshop

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=TU_CORREO@gmail.com
spring.mail.password=TU_CONTRASEÑA_DE_APLICACION
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Opcional: Para depuración
spring.mail.properties.mail.debug=true

servidor.http=http://localhost:8080